version: '3'

services:
  postgres_project:
    image: postgres:13
    environment:
      POSTGRES_USER: project_user
      POSTGRES_PASSWORD: project_password
      POSTGRES_DB: project_db
    ports:
      - "5433:5432" 
    volumes:
      - postgres-project-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "project_user"]
      interval: 5s
      retries: 5
    restart: always

volumes:
  postgres-project-db-volume: